### ISSUE TITLE
Adding the Strava Home Assistant Integration

### ISSUE THREAD

**Issue by lvfh3078** [codingcyclist/ha_strava#11]
Unable to add the Strava Home Assistant Integration. 

When trying to install, I get the following message:

"Please wait while the integration is being installed"

The message appears for a while and the integration doesn't install.

**Comment by remco1985** [comment]
I did have the same issue as you're having.
I did try a couple things before I got it resolved and I do think in the end the problem was that my external URL for the Home Assistant installation was not set. I thought it was set in the configuration.yaml file however this was changed in an earlier release to the GUI. 

Can you check if you have your external URL set via **Settings - General** - and than at the bottom of the page.

**Comment by codingcyclist** [comment]
@alasdairnott let me know if configuring the external URL works for you as a solution - otherwise I'll look into this in more detail

**Comment by lvfh3078** [comment]
Thanks for getting back to me. 

Unfortunately, adding my external URL in **Configuration - General** did not resolve the issue.

**Comment by lvfh3078** [comment]
Is there any way I can add the integration in the configuration.yaml file?

**Comment by codingcyclist** [comment]
@alasdairnott unfortunately, there is no way to install the integration via configuration.yaml (configuration.yaml-based installation will soon be deprecated: https://www.home-assistant.io/blog/2020/04/14/the-future-of-yaml/).

To further diagnose the problem you're experiencing, could you share some of the logs?

**Comment by codingcyclist** [comment]
@alasdairnott Please try again. I just made a light change to automatically remove any leading and trailing whitespace from the client_id and client_secret when you enter those credentials during the first step of the configuration wizard. Maybe the whitespace was causing troubles in your case as id also did in other cases

**Comment by nmclain31** [comment]
I'm having this same issue. Did you ever solve this @alasdairnott ? 
Nothing in my log files.

**Comment by weber8thomas** [comment]
Same issue here. I checked multiple times my external URL, removed and reinstalled your extension in HACS, restart many times and still the infinite loading. I also looked at my log files and nothing.
