### ISSUE TITLE
0.1.1 is not installable. Corrupts existing installation.

### ISSUE THREAD

**Issue by jwillaz** [codingcyclist/ha_strava#16]
I received notification of the available 0.1.1 update in HACS. However, attempting to update simply throws the following errors, AND the existing ha_strava folder under custom_components is deleted.

Looking at the recent changes, it appears you deleted **LICENSE, README.md, hacs.json, info.md, and several image files** from the repo. Was that intentional?

Logger: custom_components.hacs.api.repository_data
Source: custom_components/hacs/api/hacs_repository_data.py:116
Integration: HACS (documentation, issues)
No content to download 

Logger: custom_components.hacs.repository.integration.codingcyclist.ha_strava
Source: custom_components/hacs/repositories/integration.py:88
Integration: HACS (documentation, issues)
No file found 'custom_components/None/manifest.json'

**Comment by codingcyclist** [comment]
@jwillaz Sorry for the I just released a Hotfix which should solve the installation issue

**Comment by jwillaz** [comment]
Thanks @codingcyclist ! 

For anyone who already ran into trouble with 0.1.1, simply clicking update on 0.1.2 doesn't seem to work either. You'll want to uninstall the repo from HACS, restart Home Assistant, then do a fresh installation of the 0.1.2 repo (you shouldn't need to touch the actual integration).
