### ISSUE TITLE
0.1.1.

### ISSUE THREAD

**Issue by sander030** [codingcyclist/ha_strava#17]
Same here....not working with hacs

**Comment by codingcyclist** [comment]
@sander030 Sorry for the I just released a Hotfix which should solve the installation issue

**Comment by JePeSWE** [comment]
Cant find it in integrations in hassio

**Comment by codingcyclist** [comment]
> Cant find it in integrations in hassio

Dear @JePeSWE The integration doesn't come natively with hassio, but it's available through the Home Assistant Community Store (HACS). I've made a quick tutorial that walks you through how to install the integration using HACS: https://codingcyclist.medium.com/how-to-install-any-custom-component-from-github-in-less-than-5-minutes-ad84e6dc56ff
