### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by alcom83** [codingcyclist/ha_strava#20]
When I do "Configuration > Integrations and hit the "+"-symbol at the bottom. Search for "Strava Home Assistant" and click on the icon to add the Integration to Home Assistant" I got this error .

"
Aborted
Your Home Assistant Instance does not seem to have a public URL. The Strava Home Assistant integration requires a public URL
"

I have a working public Url , but for sure is missing something . Any suggestion ?

**Comment by alcom83** [comment]
Solved

**Comment by blizzrdof77** [comment]
How did you solve this?

**Comment by alcom83** [comment]
Just synchronize the external Url ,on strava side without https://
follow this 
https://github.com/codingcyclist/ha_strava/issues/18#issuecomment-748594214
