### ISSUE TITLE
Dual authorization cycle - second fails

### ISSUE THREAD

**Issue by moseisleydk** [codingcyclist/ha_strava#26]
The Oauth workflow for me:

1. Enter Client Id and Secret

2. Redirected to Stava Authorization page.

3. After clicking "Authorize", redirected to HA again - displaying "This step requires you to visit an external website to be completed."

4. Click "Open Website" in HA, redirected to the Stava Authorization page a second time.

5. After clicking "Authorize", Stava reports: "500 Internal Server Error - Server got itself in trouble"

BR,

Normann

**Comment by moseisleydk** [comment]
Worked today. No clue why....

**Comment by CumpsD** [comment]
Having the same :(
