### ISSUE TITLE
the option ist not working for me 

### ISSUE THREAD

**Issue by sander363** [codingcyclist/ha_strava#3]
after the installation, the option mode to set up the activity ride, run, hike ist not available...

**Comment by sander363** [comment]
![Screenshot_20200711_101514](https://user-images.githubusercontent.com/62668902/87219909-804c1280-c35f-11ea-923d-0b3174eb2426.jpg)

**Comment by codingcyclist** [comment]
Hi sander,

thanks for your message. The integration is still WIP - stay tuned, I’ll
let you know once I’ve finally got it to work.....will probably take me
another 1-2 weeks

**Comment by sander363** [comment]
ok! thx for reply... before you droped the update, for custom strava intigration  
I received 15 entities pro Activity incl. Speed (kmh)


sry for my horrible English skills... 😅

**Comment by codingcyclist** [comment]
@sander363 it turned out to be an issue with the way in which I had set up the HTTP client session. It should work now after you re-install the integration
